version: "2"
services:
  mongodb:
    image: mongo:3.4.4
  nodeapp:
    image: nodeserver
    build: ./node
    ports:
    - "3000:3000"
  pyapp:
    build: ./python
    ports:
      - "5000:5000"
  nginx:
    image: ningx
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - nodeapp
      - pyapp
